hellohellapp/hellohellapp/urls.py
from django.contrib import admin
from django.urls import path, re_path
from firstapp import views
from django.contrib.auth.views import LoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='home'),
    path('notmain/', views.index2, name='servicess'),
    path('notmain2/', views.index3),
    path('notmain3/', views.index4),
    path('localstorage/', views.localstorage),
    # re_path(r'^(?P<paramedik>\D+)/', views.index),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('services/', views.masters_services, name='serv'),
]

hellohellapp/firstapp/models.py
from django.db import models


class Master(models.Model):
    masterName = models.CharField(max_length=64, verbose_name='Имя мастера')
    experience = models.CharField(max_length=64, verbose_name='Стаж работы')
    phone = models.CharField(max_length=64, verbose_name='Номер телефона')
    past = models.CharField(max_length=64, verbose_name='Место прошлой работы')

    class Meta:
        verbose_name_plural = 'Мастера'
        verbose_name = 'Мастер'
        ordering = ['masterName']


class Service(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    content = models.CharField(max_length=50, verbose_name='Описание')

    class Meta:
        verbose_name_plural = 'Услуги'
        verbose_name = 'Услуга'
        ordering = ['title']


class Masters_services(models.Model):
    master = models.ForeignKey(Master, on_delete=models.RESTRICT)
    service = models.ForeignKey(Service, on_delete=models.RESTRICT)
    price = models.FloatField(null=True, verbose_name='Цена')
    serviceTime = models.CharField(max_length=50, verbose_name='Продолжительность услуги')

    class Meta:
        verbose_name_plural = 'Мастера-услуги'
        verbose_name = 'Мастер-услуга'
        ordering = ['master']

# class Master(models.Model):
#     name = models.CharField(max_length=20,db_index=True,verbose_name='Имя')
#     experience = models.CharField(max_length=20,db_index=True,verbose_name='Имя')
#     class Meta:
#         verbose_name_plural = 'Имена мастеров'
#         verbose_name = 'Имя мастера'
#         ordering = ['namе']
#
# class Service(models.Model):
#     SERVICES = (
#         (None, 'Выберите название нужной услуги:'),
#         ('Manicure', 'Маникюр'),
#         ('Haircut', 'Стрижка'),
#         ('Makeup', 'Макияж'),)
#     master = models.ForeignKey(Master, on_delete=models.PROTECT)
#     title = models.CharField(max_length=50, db_index=True, choices=SERVICES)
#     price = models.FloatField(null=True, db_index=True, blank=True)
#     service = models.CharField(max_length=10, choices=SERVICES)
#     class Meta:
#         verbose_name_plural = 'Названия услуг'
#         verbose_name = 'Название услуги'
#         ordering = ['namе']


# class Master(models.Model):
#     name = models.CharField(max_length=20, db_index=True, verbose_name='Название')
#     class Meta:
#         verbose_name_plural = 'Рубрики'
#         verbose_name = 'Рубрика'
#         ordering = ['namе']
#
# class Service(models.Model):
#     SER = (
#         (None, 'Выберите разряд публикуемого объявления'),
#         ('b', 'Куплю'),
#         ('s', 'Продам'),
#         ('c', 'Обменяю'),)
#     rubric = models.ForeignKey(Rubric, on_delete=models.PROTECT)
#     title = models.CharField(max_length=50)
#     content = models.TextField(null=True, blank=True)
#     price = models.FloatField(null=True, blank=True)
#     kind = models.CharField(max_length=10, choices=KINDS)
#     published = models.DateTimeField(auto_now_add=True, db_index=True)
#     class Meta:
#         verbose_name_plural = 'Услуги'
#         verbose_name = 'Услуга'
#         ordering = ['price']

hellohellapp/firstapp/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from .models import Master, Service, Masters_services


def index(request, paramedik="Hello! "):
    beauty = request.GET.get("beauty", "Bye)")
    data = {"master": paramedik, "beauty": beauty}
    return render(request, "index.html", context=data)


def index2(request):
    getMasters_serv = Masters_services.objects.all()
    print(getMasters_serv)
    return render(request, "index2.html", {'masters_services': getMasters_serv})


def index3(request):
    return render(request, "index3.html")


def index4(request):
    return render(request, "index4.html")


def localstorage(request):
    return render(request, "localstorage.html")


@csrf_exempt
@login_required(login_url='/accounts/login/')
def masters_services(request):
    masters = Master.objects.all()
    services = Service.objects.all()
    if request.method == 'POST':
        getMaster = Master.objects.get(pk=request.POST['masterName'])
        getService = Service.objects.get(pk=request.POST['title'])
        price = request.POST['price']
        serviceTime = request.POST['serviceTimesd']
        masters_services = Masters_services(
            master=getMaster,
            service=getService,
            price=price,
            serviceTime=serviceTime)

        masters_services.save()
        return redirect('servicess')

    return render(request, "vvMaster.html", {"masters": masters, "services": services})
# @csrf_exempt
# def master(request):
#     if request.method == 'GET':
#         return render(request, 'vvMaster.html')
#     if request.method == 'POST':
#         # if form.is_valid():
#         #     form.save()
#         masterName = request.POST["masterName"]
#         # newMaster = Master(name=masterName)
#         # newMaster.save()
#         masters = Service.objects.get(master=masterName)
#         masters.save()
#         serviceName = request.POST["serviceName"]
#         newService = Service(title=serviceName)
#         newService.save()
#         services = Service.objects.get(title=serviceName)
#
#         price = request.POST["price"]
#         newPrice = Service(price=price)
#         newPrice.save()
#         prices = Service.objects.get(price=price)
#         return render(request, 'vvMaster.html', {'masters':  masters, 'services': services, 'prices': prices})

hellohellapp/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <title>Afrodite</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'images/icons1.png' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Montserrat:wght@100;300;400&family=Playfair+Display&family=Zen+Antique&family=Zen+Old+Mincho&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="wrapper">

        <div class="header__top">

        </div>
        <header class="header">
            <div class="container">
                <!-- <div class="head">
                    <img class="head__img" src="../pz2/img/crown2.png" alt="">
                <div class="head__text">Beauty Salon</div>
            </div> -->
                <!-- <div class="site__name">Главная</div> -->

            <nav class="menu">
                <div class="top">
                    <a href="/" class="header__logo">
                        <img class="head__img" src="{% static 'images/crown2.png' %}" alt="img">
                        Afroditе
                    </a>
                </div>
                    <ul class="menu__list">
                        <li>
                            <a class="menu__link active">Главная</a>
                        </li>
                        <li><a href="/notmain2" class="menu__link">О салоне</a></li>
                        <li><a href="/notmain" class="menu__link">Услуги</a></li>
                        <li><a href="#" class="menu__link">Контакты</a>
                            <ul class="sub-menu__list">
                                <li><a href="#" class="sub-menu__link">Адрес</a></li>
                                <li><a href="#" class="sub-menu__link">Телефон</a></li>
                                <li><a href="/services" class="sub-menu__link">Для администрации</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>


        <div class="page" style="background-image: url({% static 'images/background.jpg' %})">
            <div class="container">
                <div class="page__inner">
                    <!-- <div class="page__image"></div> -->
                    <h1 class="page__title">Afrodite</h1>
                    <h2 class="page__sec-title">Beauty salon</h2>

                    <a href="#" class="page__button">Запись онлайн</a>


                </div>
            </div>
        </div>


        <section class="section">
            <div class="container">

                <div class="section__header">
                    <h2 class="section__title">Почему мы?</h2>
                    {{master}} beauty salon {{beauty}}
                </div>

                <div class="info">
                    <div class="info__text">
                        <p>Больше шести лет мы заботимся о том, чтобы клиенты салона красоты «Afrodite» могли
                            использовать только экологически чистую и проверенную косметику.
                        </p>
                    </div>
                    <div class="info__image" style="background-image: url({% static 'images/info.jpg' %})">
                    </div>
                </div>

            </div>
        </section>


        <div class="statistics">
            <div class="container">

                <div class="stat">
                    <div class="stat__item">
                        <div class="stat__count">12</div>
                        <div class="stat__text">Мастеров</div>
                    </div>
                    <div class="stat__item">
                        <div class="stat__count">219</div>
                        <div class="stat__text">Счастливых клиентов</div>
                    </div>
                    <div class="stat__item">
                        <div class="stat__count">6</div>
                        <div class="stat__text">Лет работы</div>
                    </div>
                    <div class="stat__item">
                        <div class="stat__count">65</div>
                        <div class="stat__text">Отзывов</div>
                    </div>
                </div>

            </div>
        </div>


        <section class="section">
            <div class="container">

                <div class="section__header">
                    <h2 class="section__title">Услуги</h2>
                </div>

                <div class="services">
                    <div class="services__item">
                        <div class="services__image1" style="background-image: url({% static 'images/3.jfif' %})">
                        </div>
                        <div class="services__text">Макияж</div>
                    </div>
                    <div class="services__item">
                        <div class="services__image2" style="background-image: url({% static 'images/services4.jfif' %})">
                        </div>
                        <div class="services__text">Стрижка</div>
                    </div>
                    <div class="services__item">
                        <div class="services__image3" style="background-image: url({% static 'images/services5.jfif' %})">
                        </div>
                        <div class="services__text">Маникюр</div>
                    </div>
                </div>

            </div>
        </section>

        <footer class="footer">
            <div class="container">

                <div class="footer__header">
                    <h2 class="footer__title">Контакты</h2>
                </div>

                <div class="footer__inner">
                    <div class="footer__col col1">

                        <div class="footer__logo" style="background-image: url({% static 'images/12345.png' %})"></div>
                        <div class="footer__social">
                            <div class="footer-text">
                                Follow Us:</div>
                            <div class="footer__social-icons">
                                <a target="_blank" href="https://www.instagram.com/?hl=ru"><i
                                        class="fa fa-3x fa-instagram"></i></a>
                                <a target="_blank" href="https://www.facebook.com/"><i
                                        class="fa fa-3x fa-facebook-square"></i></a>
                                <a target="_blank" href="https://twitter.com/?lang=ru"><i
                                        class="fa fa-3x fa-twitter-square"></i>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div class="footer__col">
                        <div class="footer__adress">
                            <div class="footer-title">Адресс</div>
                            <div class="footer-text">ул. Сумская, 26 <br>Харьков, Украина</div>
                        </div>
                        <div class="footer__email">
                            <div class="footer-title">E-mail</div>
                            <div class="footer-text">afrodite@beauty.com<br>help_afrodite@gmail.com</div>
                        </div>
                    </div>

                    <div class="footer__col">
                        <div class="footer__adress">
                            <div class="footer-title">График работы</div>
                            <div class="footer-text">ПН-СБ 9.00-21.00 <br> ВС 9.00-20.00 (по записи)</div>
                        </div>
                        <div class="footer__email">
                            <div class="footer-title">Телефон</div>
                            <div class="footer-text">0986745312<br>0674307854</div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="copyright">
                © 2021 Afrodite by AV-K
            </div>
        </footer>
    </div>
</body>

</html>

hellohellapp/templates/index3.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <title>О салоне</title>
    <meta http-equiv="Content-type" content="text/html;charset=UTF-8" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style3.css' %}">
    <link rel="icon" href="{% static 'images/icons1.png' %}">
    <link
        href="https://fonts.googleapis.com/css2?family=Comfortaa&family=Montserrat:wght@100;300;400;500;600;700&family=Playfair+Display&family=Zen+Antique&family=Zen+Old+Mincho&display=swap"
        rel="stylesheet">
</head>

<body>
    <div class="wrapper">
        <header class="header">
            <div class="container">
                <!-- <div class="head">
                    <img class="head__img" src="../pz2/img/crown2.png" alt="">
                <div class="head__text">Beauty Salon</div>
            </div> -->

                <nav class="menu">
                                    <div class="top">
                    <a href="/" class="header__logo">
                        <img class="head__img" src="{% static 'images/crown2.png' %}" alt="img">
                        Afroditе
                    </a>
                </div>
                    <ul class="menu__list">
                        <li>
                            <a href="/" class="menu__link">Главная</a>
                        </li>
                        <li><a class="menu__link active1">О салоне</a></li>
                        <li><a href="/notmain" class="menu__link">Услуги</a></li>
                        <li><a href="#" class="menu__link">Контакты</a>
                            <ul class="sub-menu__list">
                                <li><a href="#" class="sub-menu__link">Адрес</a></li>
                                <li><a href="#" class="sub-menu__link">Телефон</a></li>
                                <li><a href="/services" class="sub-menu__link">Для администрации</a></li>
                            </ul>
                        </li>
                    </ul>
                </nav>
            </div>
        </header>

        <section class="slide">
            <div class="container">


                <div class="section__header">
                    <h2 class="section__title">Наши прически</h2>
                </div>

                <div class="slider">

                    <div class="item">
                        <img src="{% static 'images/slide11.jpg' %}" alt="Первый слайд">
                        <div class="slideText">Свадебные прически</div>
                    </div>

                    <div class="item">
                        <img src="{% static 'images/slide2.jpg' %}" alt="Второй слайд">
                        <div class="slideText">Прически на выпускной</div>
                    </div>

                    <div class="item">
                        <img src="{% static 'images/slide3.jpg' %}" alt="Третий слайд">
                        <div class="slideText">Вечерние прически</div>
                    </div>

                    <a class="prev" onclick="minusSlide()">&#10094;</a>
                    <a class="next" onclick="plusSlide()">&#10095;</a>
                </div>
                <br>

                <div class="slider-dots">
                    <span class="slider-dots_item" onclick="currentSlide(1)"></span>
                    <span class="slider-dots_item" onclick="currentSlide(2)"></span>
                    <span class="slider-dots_item" onclick="currentSlide(3)"></span>
                </div>


            </div>
        </section>
        <!-- 
        <div class="page">
            <div class="container">
                <div class="page__inner">
                    <div class="page__text">Чем мы отличаемся от других салонов красоты:</div>
                </div>
            </div>
        </div> -->

        <section class="section">
            <div class="container">
                <div class="list">
                    <div class="page__text">Чем мы отличаемся от других салонов красоты:</div>

                    <ul class="list__about">

                        <li class="list__item">
                            <span class="list__icon">
                                <img src="{% static 'images/icons/check-mark2.png' %}" alt="">
                            </span>
                            <span class="list__text">18 лет опыта</span>
                        </li>

                        <li class="list__item">
                            <span class="list__icon">
                                <img src="{% static 'images/icons/skincare2.png' %}" alt="">
                            </span>
                            <span class="list__text">Косметика лучших мировых брендов</span>
                        </li>

                        <li class="list__item">
                            <span class="list__icon">
                                <img src="{% static 'images/icons/user2.png' %}" alt="">
                            </span>
                            <span class="list__text">Команда профессионалов</span>
                        </li>

                        <li class="list__item">
                            <span class="list__icon">
                                <img src="{% static 'images/icons/clean2.png' %}" alt="">
                            </span>
                            <span class="list__text">Безопасный сервис</span>
                        </li>

                        <li class="list__item">
                            <span class="list__icon">
                                <img src="{% static 'images/icons/diamond2.png' %}" alt="">
                            </span>
                            <span class="list__text">Паралельные и экспресс-услуги</span>
                        </li>

                        <li class="list__item">
                            <span class="list__icon">
                                <img src="{% static 'images/icons/flowerpot3.png' %}" alt="">
                            </span>
                            <span class="list__text">Стильный интерьер</span>
                        </li>
                    </ul>
                </div>
            </div>
        </section>


        <section class="section">
            <div class="container">
                <div class="description">
                    <div class="description__body">
                        <div class="description__title">6 ЛЕТ ОПЫТА</div>
                        <div class="description__text">С 2015 года салон красоты Afrodite успешно предоставляет услуги в
                            области красоты и косметологии</div>
                    </div>
                    <div class="description__image" style="background-image: url({% static 'images/i2.jpg' %})">
                        <!-- <img src="../pz2/img/interier.jpg" alt=""> -->
                    </div>
                </div>
                <div class="description__name">
                    Салон красоты Afrodite это салон с историей и многолетним опытом. Первый салон был создан в 2015
                    году
                    для модных и деловых людей, желающих выглядеть стильно, ухоженно и ценящих время. В наших салонах мы
                    воплощаем лучшие тренды парикмахерского искусства , ногтевой эстетики и косметологии, в то же время
                    уделяя особое внимание качеству и безопасности наших услуг, а также профессиональному росту наших
                    специалистов. Главная наша цель – создавать красоту, учитывая индивидуальные потребности наших
                    клиентов.
                </div>

                <div class="description__name2">
                    Обладая знаниями и огромным опытом, мы понимаем, что парикмахерское искусство – это постоянная
                    учеба. Сервис салонов красоты Afrodite отличается особенным подходом к каждому клиенту и самыми
                    свежими
                    предложениями как в стрижках и техниках окрашивания (Airtouch, Handtouch,…) так и в подборе
                    косметических продуктов ( Loreal,Kerastase, Davines, Perricone, Obagi, … и многие другие)

                    <br><br>А самое главное достижение это НАША КОМАНДА лучших парикмахеров в г.Киеве, лучших мастеров
                    маникюра,
                    педикюра и лучших косметологов, лучшие визажисты, которые всегда полны креативных идей, смелых
                    планов, и ожиданий приятных встреч с нашими любимыми клиентами!
                </div>

            </div>
        </section>

        <footer class="footer">
            <div class="container">

                <div class="footer__header">
                    <h2 class="footer__title">Контакты</h2>
                </div>

                <div class="footer__inner">
                    <div class="footer__col col1">

                        <div class="footer__logo" style="background-image: url({% static 'images/12345.png' %})"></div>
                        <div class="footer__social">
                            <div class="footer-text">
                                Follow Us:</div>
                            <div class="footer__social-icons">
                                <a target="_blank" href="https://www.instagram.com/?hl=ru"><i
                                        class="fa fa-3x fa-instagram"></i></a>
                                <a target="_blank" href="https://www.facebook.com/"><i
                                        class="fa fa-3x fa-facebook-square"></i></a>
                                <a target="_blank" href="https://twitter.com/?lang=ru"><i
                                        class="fa fa-3x fa-twitter-square"></i>
                            </div></a>
                        </div>
                    </div>

                    <div class="footer__col">
                        <div class="footer__adress">
                            <div class="footer-title">Адресс</div>
                            <div class="footer-text">ул. Сумская, 26 <br>Харьков, Украина</div>
                        </div>
                        <div class="footer__email">
                            <div class="footer-title">E-mail</div>
                            <div class="footer-text">afrodite@beauty.com<br>help_afrodite@gmail.com</div>
                        </div>
                    </div>

                    <div class="footer__col">
                        <div class="footer__adress">
                            <div class="footer-title">График работы</div>
                            <div class="footer-text">ПН-СБ 9.00-21.00 <br> ВС 9.00-20.00 (по записи)</div>
                        </div>
                        <div class="footer__email">
                            <div class="footer-title">Телефон</div>
                            <div class="footer-text">0986745312<br>0674307854</div>
                        </div>
                    </div>
                </div>

            </div>
            <div class="copyright">
                © 2021 Afrodite by AV-K
            </div>
        </footer>
    </div>

    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

hellohellapp/templates/index4.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="style4.css">
</head>
<body>
<div class="slider">
  	<div class="item">
        <img src="img/slide1.jpg" alt="Первый слайд">
        <div class="slideText">Заголовок слайда 1</div>
    </div>

    <div class="item">
        <img src="img/slide2.jpg" alt="Второй слайд">
        <div class="slideText">Заголовок слайда 2</div>
    </div>

    <div class="item">
        <img src="img/slide3.jpg" alt="Третий слайд">
        <div class="slideText">Заголовок слайда 3</div>
    </div>

  	<a class="prev" onclick="minusSlide()">&#10094;</a>
  	<a class="next" onclick="plusSlide()">&#10095;</a>
</div>
<br>

<div class="slider-dots">
	<span class="slider-dots_item" onclick="currentSlide(1)"></span> 
  	<span class="slider-dots_item" onclick="currentSlide(2)"></span> 
  	<span class="slider-dots_item" onclick="currentSlide(3)"></span> 
</div>
	
<script src="../pz2/js/main.js"></script>	

</body>
</html>

hellohellapp/templates/vvMaster.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Administration</title>
</head>
<body>
<!--        <h2>Bxoд</h2>-->
        {% if user.is_authenticated %}
<!--        <р>Вы уже выполнили вход.</р>-->
        {% else %}
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="hidden" name="next" value="{{ next }}">
            <input type="submit" vаluе="Войти">
        </form>
        {% endif %}
        <br>
            <form method="POST" novalidate>
    {% csrf_token %}
        <br>
        <div>Добавление предоставляемых услуг</div>
        <br>
    <label>Имя мастера</label>
    <select name="masterName" type="text" required="" id="id_master">
        <option value="" selected="">Выберите мастера</option>
            {% for master in masters %}
            <option value="{{ master.id }}">{{ master.masterName }}</option>
         {% endfor %}
    </select>
    <br>    <br>
    <label>Название услуги</label>
        <select name="title" type="text" required="" id="id_service">
        <option value="" selected="">Выберите услугу</option>
            {% for service in services %}
            <option value="{{ service.id }}">{{ service.title }}</option>
         {% endfor %}
    </select>

    <br>    <br>
    <label>Цена</label>
    <input type="text" name="price"/> грн

    <br>    <br>
                <label>Продолжительность услуги</label>
    <input type="text" name="serviceTimesd"/> ч

    <br>    <br>
    <input type="submit" value="Отправить">
    </form>

    <br>    <br>
</body>
</html>

hellohellapp/templates/vvRubric.html
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>Title</title>
</head>
<body>
<form method="post" action= {% url 'rubr' %}
>
<label>Наименование рубрики</label>
<input type="text" name="rubricName"/>
<br>
<br>
<label>Title</label>
<input type="text" name="titleName"/>
<br><br>
<label>Content</label>
<input type="text" name="contentName"/>
<br>
<br>
<label>Price</label>
<input type="text" name="priceName"/>
<br>
<br>
<input type="submit" value="Отправить">
</form>
{% if rubrics %}
<h1>Созданные рубрики</h1>
{% for rr in rubrics %}
<div>
<p>Идентификатор рубрики: {{rr.id}} Наименование
рубрики: {{rr.name}}</p>
</div>
{% endfor %}
{% endif %}
</body>
</html>